services:
  development:
    build:
      context: .
      target: development
    image: todo_app:dev
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: ./todo_app
        target: //todo_app/todo_app
  production:
    build:
      context: .
      target: production
    image: todo_app:prod
    env_file:
      - .env
    environment:
      - FLASK_ENV=production
    ports:
    - "80:80"
  testing:
    build:
      context: .
      target: testing
    command: [ "todo_app/tests_e2e", "todo_app/tests" ]
    image: todo_app:test
    env_file:
      - .env
    environment:
      - FLASK_ENV=testing
    volumes:
      - type: bind
        source: ./todo_app
        target: //todo_app/todo_app
    ports:
      - "8080:8080"