name: Continuous Integration Pipeline
on: [push]
jobs:
  build:
    name: Build and run unit and integration tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        docker build --target testing --tag todo-app:test .
        docker run --env-file ./.env -p 8080:8080 --mount type=bind,source="$(pwd)"/todo_app,target=/todo_app/todo_app todo-app:test todo_app/tests_e2e
        docker run -p 8080:8080 --mount type=bind,source="$(pwd)"/todo_app,target=/todo_app/todo_app todo-app:test todo_app/tests